//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chapter
    {
        public Chapter()
        {
            this.Topics = new HashSet<Topic>();
        }
    
        public int ChapterID { get; set; }
        public byte SubjectID { get; set; }
        public string ChapterName { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual ICollection<Topic> Topics { get; set; }
    }
}
