//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choice
    {
        public Choice()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public long ChoiceID { get; set; }
        public long QuestionID { get; set; }
        public string ChoiceDisplay { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}
