//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MCQ
    {
        public MCQ()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public int MCQID { get; set; }
        public short Duration { get; set; }
        public long ArticleID { get; set; }
        public string Title { get; set; }
        public int DisplayQuestion { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}
