//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public Topic()
        {
            this.Articles = new HashSet<Article>();
        }
    
        public int TopicID { get; set; }
        public int ChapterID { get; set; }
        public string TopicName { get; set; }
        public int TotalArticles { get; set; }
        public long MasterArticleID { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual Chapter Chapter { get; set; }
    }
}
