//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UGEEntities : DbContext
    {
        public UGEEntities()
            : base("name=UGEEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<ArticleMistake> ArticleMistakes { get; set; }
        public virtual DbSet<Bookmark> Bookmarks { get; set; }
        public virtual DbSet<Chapter> Chapters { get; set; }
        public virtual DbSet<Choice> Choices { get; set; }
        public virtual DbSet<MCQ> MCQs { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<ReplyAgainstMistake> ReplyAgainstMistakes { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WatchedReference> WatchedReferences { get; set; }
        public virtual DbSet<WishList> WishLists { get; set; }
    }
}
