//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UGE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WatchedReference
    {
        public long WatchedReferenceID { get; set; }
        public long WhichFromArticleID { get; set; }
        public long WhichToArticleID { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual Article Article1 { get; set; }
    }
}
